version: 2.1

parameters:
  action:
    type: enum
    enum: [oncommit, docker]
    default: oncommit

  docker_img_version:
    # Docker image version for running tests.
    type: string
    default: "a0d53ea"

workflows:
  test-jobs:
    when:
      equal: [oncommit, << pipeline.parameters.action >>]
    jobs:
      - format-and-mypy:
          context:
            - ghcr-auth
      - pytype:
          context:
            - ghcr-auth
      - py-tests:
          context:
            - ghcr-auth

commands:
  save-worker-test-results:
    steps:
      - store_test_results: # report the test results (in test-results/junit.xml) to CircleCI
          path: /workspace/test-results

jobs:
  format-and-mypy:
    docker:
      - image: ghcr.io/alignmentresearch/learned-planners:<< pipeline.parameters.docker_img_version >>
        auth:
          username: "$GHCR_DOCKER_USER"
          password: "$GHCR_DOCKER_TOKEN"
    resource_class: large
    working_directory: /workspace/third_party/stable-baselines3
    steps:
      - checkout
      - run:
          name: Sort imports (ruff), check style (black)
          command: make check-codestyle
      - run:
          name: Lint (ruff)
          command: ruff .
      - run:
          name: Typecheck (mypy)
          command: mypy .
  pytype:
    docker:
      - image: ghcr.io/alignmentresearch/learned-planners:<< pipeline.parameters.docker_img_version >>
        auth:
          username: "$GHCR_DOCKER_USER"
          password: "$GHCR_DOCKER_TOKEN"
    resource_class: large
    working_directory: /workspace/third_party/stable-baselines3
    steps:
      - checkout
      - run: pytype -j 4
  py-tests:
    docker:
      - image: ghcr.io/alignmentresearch/learned-planners:<< pipeline.parameters.docker_img_version >>
        auth:
          username: "$GHCR_DOCKER_USER"
          password: "$GHCR_DOCKER_TOKEN"
    resource_class: medium
    working_directory: /workspace/third_party/stable-baselines3
    parallelism: 16
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            /workspace/dist_test.py -c circleci_worker --worker-out-dir /workspace/test-results . -k 'not test_save_load_large_model'
          environment:
            OMP_NUM_THREADS: "2"
      - save-worker-test-results
